### ISSUE TITLE
Erro ao Adicionar Primeiro Bloco de Aproveitamento num Primeiro Aproveitamento

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#1]
O erro

"TypeError: Cannot read property 'N610:CB0534' of undefined"

aconteceu após tentativa de cadastro de um novo bloco de aproveitamento num novo aproveitamento.

Rota para o erro:
1. Partindo da base de dados inicial (vazia), foram fornecidas as configurações iniciais (instituição de destino, etc).
2. Foi iniciado um novo aproveitamento, cadastrando o necessário até chegar à seleção dos blocos de aproveitamento.
3. Iniciando o cadastro de um bloco de aproveitamento 1-para-1, foram cadastradas todas as informações necessárias para completar o bloco de aproveitamento, e, quando o bloco ia ser concluído e trazido para o aproveitamento, aconteceu o erro.

![Captura de tela de 2020-04-13 23-26-46](https://user-images.githubusercontent.com/26823279/79179599-5de93e00-7dde-11ea-88c2-1850e5710e52.png)

**Comment by JsBatista** [comment]
Refiz todos os passos que foram feitos pelo senhor e não consegui reproduzir o erro.
Tentarei depois reproduzir o erro em outra máquina para ver se consigo dessa vez, pois atualmente consigo cadastrar novos blocos e também finalizar o aproveitamento completamente.

Se possível, talvez seja interessante o senhor tentar reproduzir o erro registrando todos os passos feitos até o erro acontecer, um vídeo seria ótimo, mas, se não ,possível, vou precisar de mais detalhes.

**Comment by pablo-m-s-farias** [comment]
Olá, @JsBatista .

Acabo de encontrar esse tipo de problema novamente.

Não guardei um passo-a-passo detalhado do caminho que levou ao erro, mas não há dificuldade em reproduzir o caminho, pois fiz, em ordem, apenas o essencial para realizar um primeiro aproveitamento, chegando no erro exatamente ao concluir o cadastro do primeiro bloco de aproveitamento, a partir da tela de novo aproveitamento.

Em alto nível, o que fiz foi:

1. Baixar o programa (commit a357ca8).
2. npm i (com Node.js v12.16.2 e npm@6.14.4)
3. Executar o programa pela primeira vez (npm run electron-dev)
4. Preencher as configurações iniciais (CC-UFC e 75%).
5. Iniciar um novo aproveitamento (UECE -> UFC), preenchendo os campos em ordem.
6. Exatamente no ponto de concluir o cadastro do primeiro bloco (CT868 + CT871 + CT879 -> CB0534 + CB0535, as primeiras de 68h, as últimas de 96h), aconteceu o erro abaixo.

Sugiro você tentar reproduzir o caminho acima. Se o erro não acontecer, veja se os seus npm e nodejs têm as versões indicadas acima.

![Captura de tela de 2020-05-13 16-24-42](https://user-images.githubusercontent.com/26823279/81857359-8dec4400-9538-11ea-858a-d5c7676a0989.png)

**Comment by JsBatista** [comment]
Adicionado tratamento a esse erro na versão mais recente. Restam testes a serem feitos antes de fechar a issue.

**Comment by JsBatista** [comment]
Issue não ocorreu depois de serem feitos testes após o commit 8d7fed5
. Fechando a issue até que esse erro volte a aparecer.
