### ISSUE TITLE
Vulnerabilidades de Segurança em yarn.lock

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#2]
O GitHub automaticamente avisou:

------------------------------
Known **high severity** security vulnerability detected in **handlebars < 4.3.0** defined in [yarn.lock](https://github.com/UFC-CC-CC/AutoVeitamento/blob/master/yarn.lock).

Known **high severity** security vulnerability detected in **minimist < 0.2.1** defined in yarn.lock. 

Known **moderate severity** security vulnerability detected in **serialize-javascript < 2.1.1** defined in yarn.lock. 

Known **moderate severity** security vulnerability detected in **kind-of < 6.0.3** defined in yarn.lock. 

Known **moderate severity** security vulnerability detected in **acorn >= 6.0.0, < 6.4.1** defined in yarn.lock.

------------------------------

**Comment by JsBatista** [comment]
Acabei de ver todas essas falhas, acredito que são pacotes não atualizados no próprio react, verei se essas vulnerabilidades são realmente preocupantes e, se forem, irei atualizar os pacotes.

**Comment by JsBatista** [comment]
Os pacotes foram atualizados, um via o próprio github, e, até então, não há mais alertas de segurança. Fechando a issue.
