### ISSUE TITLE
Campo de Nota, Semestre etc não aparece para Bloco de Aproveitamento em Novo Aproveitamento

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#4]
Executado com NodeJS versão 12.16.2 e npm versão 6.14.4, a partir do commit 288a07c:

0. git clone https://github.com/UFC-CC-CC/AutoVeitamento

1. npm i

2. npm run electron-dev

3. Configurações -> Editar Configurações.

3.1. Selecionar, cadastrando, a Instituição de Destino.

3.2. Selecionar, cadastrando, o Coordenador.

3.2.1. Para isso, cadastrar a Unidade de Lotação do Coordenador.

3.3. Selecionar, cadastrando, o Curso de Destino.

3.4. Selecionar a porcentagem 75% para os blocos.

3.5. Selecionar, cadastrando, a Cidade.

3.6. Salvar Alterações.

4. Realizar Novo Aproveitamento.

4.1. Selecionar, cadastrando, um novo aluno para o aproveitamento.

4.2. Selecionar o Coordenador como Responsável.

4.3. Selecionar, cadastrando, uma Instituição de Origem.

4.4. Informar a data (no caso: 09/01/2020).

4.5. Informar um número de processo.

4.6. Função do Responsável: Coordenador.

4.7. Selecionar, cadastrando, novo bloco de aproveitamento.

4.7.1. Manter a Data e o Solicitador pré-preenchidos.

4.7.2. Deixar Parecerista vazio.

4.7.3. Selecionar, cadastrando, uma disciplina cursada, de 72 horas.

4.7.4. Selecionar, cadastrando, uma disciplina aproveitada, de 96 horas.

4.7.5. Manter as Observações vazias.

4.8. Cadastrar o bloco de aproveitamento.

--- A [Issue 1](https://github.com/UFC-CC-CC/AutoVeitamento/issues/1) devia ter acontecido aqui, mas não consegui reproduzir. ---

4.9. Preencher nota, semestre e carga horária aproveitada (72 -> 96) do 1o bloco.

4.10. Selecionar, cadastrando, 2o bloco de aproveitamento (1-para-1, 36h -> 32h).

--- Aqui, o programa não travou, mas não apareceu o bloco visual para digitação da nota e etc relativo ao segundo bloco de aproveitamento: ver a captura de tela abaixo.

![bloco_visual_faltando](https://user-images.githubusercontent.com/26823279/79270172-01386280-7e74-11ea-8097-149a1051348b.jpg)

**Comment by JsBatista** [comment]
Issue não ocorreu depois de serem feitos testes após o commit 8d7fed5
. Fechando a issue até que esse erro volte a aparecer.
