### ISSUE TITLE
Aviso Errado sobre Porcentagem Mínima de Carga Horária de Bloco de Aproveitamento

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#5]
A mesma sequência de passos da [Issue 4](https://github.com/UFC-CC-CC/AutoVeitamento/issues/4), incluindo a captura de tela resultante, mostra que o programa informou

> Atenção! Os seguintes blocos de aproveitamento não condizem com a porcentagem mínima de horas configurada: (75%)
> N610 aproveitando CB0534

no caso de um bloco 1-para-1 em que a origem tem 72h e o destino 96h, sendo que 72h é exatamente 75% de 96h, ou seja, a carga horária está dentro do limite, e portanto não deveria haver aviso.

**Comment by JsBatista** [comment]
O erro foi reproduzido, identificado e corrigido no commit que realizei agora. Fechando issue.
