### ISSUE TITLE
Horas Aproveitadas Sobrescritas após Incluir Novo Bloco em Aproveitamento

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#7]
No commit 8d7fed5, ao editar-se um aproveitamento consolidado, se o usuário altera as horas aproveitadas de disciplinas de blocos já presentes no aproveitamento, e em seguida inclui, cadastrando, um novo bloco de aproveitamento, as horas aproveitadas digitadas são sobrescritas pelo valor padrão (média). Isso ocorre toda vez que, na tela do aproveitamento, um novo bloco é incluído mediante cadastro.

**Comment by JsBatista** [comment]
Erro consertado no commit 102fe0c
