### ISSUE TITLE
Data do Aproveitamento: Sempre Gravando a de Edição, Sobrescreve a do Usuário

### ISSUE THREAD

**Issue by pablo-m-s-farias** [UFC-CC-CC/AutoVeitamento#8]
No commit 8d7fed5, a data que está sendo gravada nos aproveitamentos é aquela do momento da edição, mesmo quando, iniciada a edição, o usuário fornece outra data. É possível verificar esse fato consultando o aproveitamento consolidado, e também lendo o relatório gerado ao fim de uma edição.

**Comment by JsBatista** [comment]
Erro consertado no commit 102fe0c
